---
background:
 - path:
   - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/background/ntuple_ZeroBias_2023D_100k.h5'
   name: 'ntuple ZeroBias 2023D'
   use: True

signal:
 - path:
   - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/signal/ntuple_HTo2LongLivedTo4b_MH-125_MFF-25_CTau-1500mm.h5'
   name: 'HTo2LongLivedTo4b'
   use: True
 - path:
   - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/signal/ntuple_RelValTTbar_SemiLeptonic.h5'
   name: 'RelValTTbar_SemiLeptonic'
   use: True
 - path:
   - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/signal/ntuple_VBFHToTauTau_M125.h5'
   name: 'VBFHToTauTau' 
   use: True

exposure:
 training:
  - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/background/ntuple_ZeroBias_2023D_100k_0.h5'
 validation:
  - '/nfs_scratch/zxlin/cicada_100k/inputs/h5/background/ntuple_ZeroBias_2023D_100k_1.h5'
